services:
  php:
    build: .
    container_name: mini-erp-laravel
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel_user
      DB_PASSWORD: laravel_pass
    expose:
      - 9000
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: mini-erp-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5439:5432"

volumes:
  pgdata:
